### ISSUE TITLE
Displaying code in index.html files

### ISSUE THREAD

**Issue by adamnbowen** [tcorral/Design-Patterns-in-Javascript#1]
If you had a minimal amount of css in your .html files, you could display the code present when people open it (so they can see the code while they play with the console:

``` css
script {
    display: block;
    white-space: pre;
}
```
